import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainHeader from '../components/main-header/main-header';
import "./globals.css";
import AuthProvider from "./context/AuthProvider"
import { useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body>
          <MainHeader/>
        {children}
        </body>
    </html>
  );
}
